// web-react/src/pages/system/dict/DictSubItemsModal.tsx
import { useEffect, useState } from 'react';
import type { ColumnsType } from 'antd/es/table';
import { App, Button, Space, Table, Tag } from 'antd';
import { PlusOutlined } from '@ant-design/icons';
import type { DictRecord } from '@/types/system';
import { dictApi } from '@/api/dict';
import { BasicModal } from '@/components/common/BasicModal';
import { TableAction } from '@/components/common/TableAction';
import { DictModal } from './DictModal';

interface DictSubItemsModalProps {
  open: boolean;
  parentId?: number;
  onCancel: () => void;
}

export function DictSubItemsModal({
  open,
  parentId,
  onCancel,
}: DictSubItemsModalProps) {
  const { message } = App.useApp();
  const [loading, setLoading] = useState(false);
  const [subItems, setSubItems] = useState<DictRecord[]>([]);
  const [itemModalOpen, setItemModalOpen] = useState(false);
  const [currentItemId, setCurrentItemId] = useState<number>();

  const loadSubItems = async () => {
    if (!parentId) {
      setSubItems([]);
      return;
    }

    setLoading(true);
    try {
      const parent = await dictApi.detail(parentId);
      const items = await dictApi.getByType(parent.dictType, parentId);
      setSubItems(items);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (open) {
      void loadSubItems();
    }
  }, [open, parentId]);

  const columns: ColumnsType<DictRecord> = [
    { title: '字典标签', dataIndex: 'dictLabel', width: 180 },
    { title: '字典键值', dataIndex: 'dictValue', width: 160 },
    { title: '排序', dataIndex: 'sort', width: 100 },
    {
      title: '默认',
      dataIndex: 'isDefault',
      width: 100,
      render: (value) => <Tag color={value ? 'success' : 'default'}>{value ? '是' : '否'}</Tag>,
    },
    {
      title: '状态',
      dataIndex: 'status',
      width: 100,
      render: (value) => (
        <Tag color={value === 0 ? 'success' : 'error'}>
          {value === 0 ? '正常' : '停用'}
        </Tag>
      ),
    },
    {
      title: '操作',
      key: 'action',
      width: 180,
      render: (_, record) => (
        <TableAction
          actions={[
            {
              key: 'edit',
              label: '编辑',
              onClick: () => {
                setCurrentItemId(record.id);
                setItemModalOpen(true);
              },
            },
            {
              key: 'delete',
              label: '删除',
              danger: true,
              confirmTitle: '确定删除该子项吗？',
              onClick: async () => {
                await dictApi.delete(record.id);
                message.success('删除成功');
                await loadSubItems();
              },
            },
          ]}
        />
      ),
    },
  ];

  return (
    <>
      <BasicModal
        open={open}
        title="编辑字典子项"
        width={920}
        footer={null}
        onCancel={onCancel}
      >
        <div className="page-toolbar">
          <Space>
            <Button
              icon={<PlusOutlined />}
              type="primary"
              onClick={() => {
                setCurrentItemId(undefined);
                setItemModalOpen(true);
              }}
            >
              新增子项
            </Button>
          </Space>
        </div>
        <Table<DictRecord>
          columns={columns}
          dataSource={subItems}
          loading={loading}
          pagination={false}
          rowKey="id"
        />
      </BasicModal>

      <DictModal
        open={itemModalOpen}
        dictId={currentItemId}
        parentId={parentId}
        onCancel={() => setItemModalOpen(false)}
        onSuccess={() => {
          setItemModalOpen(false);
          void loadSubItems();
        }}
      />
    </>
  );
}

// web/src/views/system/dict/DictSubItemsModal.vue
<template>
  <BasicModal
    v-model:visible="visible"
    title="编辑字典子项"
    :width="900"
    :footer="null"
    @cancel="handleCancel"
  >
    <div class="dict-subitems">
      <a-button type="primary" @click="handleAdd" style="margin-bottom: 16px">
        <template #icon><PlusOutlined /></template>
        新增子项
      </a-button>
      
      <BasicTable
        :columns="columns"
        :data-source="subItems"
        :pagination="false"
        :show-action-column="true"
      >
        <template #bodyCell="{ column, record }">
          <template v-if="column.dataIndex === 'isDefault'">
            <a-tag :color="record.isDefault ? 'success' : 'default'">
              {{ record.isDefault ? '是' : '否' }}
            </a-tag>
          </template>
          <template v-else-if="column.dataIndex === 'status'">
            <a-tag :color="record.status === 0 ? 'success' : 'error'">
              {{ record.status === 0 ? '正常' : '停用' }}
            </a-tag>
          </template>
          <template v-else-if="column.dataIndex === 'action'">
            <TableAction
              :actions="[
                {
                  label: '编辑',
                  onClick: () => handleEditItem(record),
                },
                {
                  label: '删除',
                  color: 'error',
                  popConfirm: {
                    title: '确定删除该子项吗？',
                    confirm: () => handleDeleteItem(record.id),
                  },
                },
              ]"
            />
          </template>
        </template>
      </BasicTable>
    </div>

    <DictModal
      v-model:visible="itemModalVisible"
      :id="currentItemId"
      :parent-id="parentId"
      @success="handleItemSuccess"
    />
  </BasicModal>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue';
import { message } from 'ant-design-vue';
import { PlusOutlined } from '@ant-design/icons-vue';
import BasicModal from '@/components/Modal/BasicModal.vue';
import BasicTable from '@/components/Table/BasicTable.vue';
import TableAction from '@/components/Table/TableAction.vue';
import DictModal from './DictModal.vue';
import { dictApi } from '@/api/dict';
import type { Dict } from '@/api/dict';

const props = defineProps<{
  visible: boolean;
  parentId?: number;
}>();

const emit = defineEmits<{
  (e: 'update:visible', value: boolean): void;
}>();

const visible = ref(false);
const subItems = ref<Dict[]>([]);
const itemModalVisible = ref(false);
const currentItemId = ref<number>();

const columns = [
  { title: '字典标签', dataIndex: 'dictLabel', width: 150 },
  { title: '字典键值', dataIndex: 'dictValue', width: 150 },
  { title: '排序', dataIndex: 'sort', width: 80 },
  { title: '是否默认', dataIndex: 'isDefault', width: 80 },
  { title: '状态', dataIndex: 'status', width: 80 },
  { title: '操作', dataIndex: 'action', width: 150 },
];

const loadSubItems = async () => {
  if (!props.parentId) return;
  try {
    const parent = await dictApi.detail(props.parentId);
    const items = await dictApi.getByType(parent.dictType, props.parentId);
    subItems.value = items;
  } catch (error) {
    console.error('加载子项失败:', error);
  }
};

const handleAdd = () => {
  currentItemId.value = undefined;
  itemModalVisible.value = true;
};

const handleEditItem = (record: any) => {
  currentItemId.value = record.id;
  itemModalVisible.value = true;
};

const handleDeleteItem = async (id: number) => {
  try {
    await dictApi.delete(id);
    message.success('删除成功');
    loadSubItems();
  } catch (error) {
    console.error('删除失败:', error);
  }
};

const handleItemSuccess = () => {
  itemModalVisible.value = false;
  loadSubItems();
};

const handleCancel = () => {
  emit('update:visible', false);
};

watch(() => props.visible, (val) => {
  visible.value = val;
  if (val) {
    loadSubItems();
  }
});

watch(visible, (val) => {
  emit('update:visible', val);
});
</script>

<style scoped lang="less">
.dict-subitems {
  min-height: 300px;
}
</style>
