// web-react/src/pages/system/dict/index.tsx
import { useRef, useState } from 'react';
import type { ColumnsType } from 'antd/es/table';
import { App, Button, Popconfirm, Space, Tag } from 'antd';
import { DeleteOutlined, PlusOutlined } from '@ant-design/icons';
import { BasicTable, type BasicTableRef } from '@/components/common/BasicTable';
import { PermissionGate } from '@/components/common/PermissionGate';
import { TableAction } from '@/components/common/TableAction';
import type { FormSchema } from '@/types/form';
import type { DictRecord } from '@/types/system';
import { dictApi } from '@/api/dict';
import { DictModal } from './DictModal';
import { DictSubItemsModal } from './DictSubItemsModal';

const searchSchemas: FormSchema[] = [
  {
    name: 'dictType',
    label: '字典类型',
    component: 'Input',
    colProps: { span: 8 },
  },
  {
    name: 'dictLabel',
    label: '字典标签',
    component: 'Input',
    colProps: { span: 8 },
  },
  {
    name: 'status',
    label: '状态',
    component: 'Select',
    colProps: { span: 8 },
    props: {
      allowClear: true,
      options: [
        { label: '正常', value: 0 },
        { label: '停用', value: 1 },
      ],
    },
  },
];

export default function DictPage() {
  const { message } = App.useApp();
  const tableRef = useRef<BasicTableRef<DictRecord>>(null);
  const [modalOpen, setModalOpen] = useState(false);
  const [subItemsOpen, setSubItemsOpen] = useState(false);
  const [currentDictId, setCurrentDictId] = useState<number>();
  const [currentParentId, setCurrentParentId] = useState<number>();

  const columns: ColumnsType<DictRecord> = [
    { title: '字典 ID', dataIndex: 'id', width: 100 },
    { title: '字典类型', dataIndex: 'dictType', width: 160 },
    { title: '字典标签', dataIndex: 'dictLabel', width: 160 },
    { title: '字典键值', dataIndex: 'dictValue', width: 160 },
    { title: '排序', dataIndex: 'sort', width: 100 },
    {
      title: '默认',
      dataIndex: 'isDefault',
      width: 100,
      render: (value) => <Tag color={value ? 'success' : 'default'}>{value ? '是' : '否'}</Tag>,
    },
    {
      title: '状态',
      dataIndex: 'status',
      width: 100,
      render: (value) => (
        <Tag color={value === 0 ? 'success' : 'error'}>
          {value === 0 ? '正常' : '停用'}
        </Tag>
      ),
    },
    { title: '创建时间', dataIndex: 'createdTime', width: 180 },
    {
      title: '操作',
      key: 'action',
      width: 220,
      fixed: 'right',
      render: (_, record) => (
        <TableAction
          actions={[
            {
              key: 'edit',
              label: '编辑',
              permission: 'dict.update',
              onClick: () => {
                setCurrentDictId(record.id);
                setModalOpen(true);
              },
            },
            {
              key: 'subItems',
              label: '编辑子项',
              permission: 'dict.update',
              onClick: () => {
                setCurrentParentId(record.id);
                setSubItemsOpen(true);
              },
            },
            {
              key: 'delete',
              label: '删除',
              permission: 'dict.delete',
              danger: true,
              confirmTitle: '确定删除该字典吗？',
              onClick: async () => {
                await dictApi.delete(record.id);
                message.success('删除成功');
                tableRef.current?.reload();
              },
            },
          ]}
        />
      ),
    },
  ];

  return (
    <>
      <BasicTable<DictRecord>
        ref={tableRef}
        columns={columns}
        fetchData={dictApi.page}
        rowKey="id"
        searchSchemas={searchSchemas}
        scroll={{ x: 1300 }}
        toolbar={
          <Space>
            <PermissionGate permission="dict.create">
              <Button
                icon={<PlusOutlined />}
                type="primary"
                onClick={() => {
                  setCurrentDictId(undefined);
                  setModalOpen(true);
                }}
              >
                新增
              </Button>
            </PermissionGate>
            <PermissionGate permission="dict.delete">
              <Popconfirm
                title="确定批量删除选中的字典吗？"
                onConfirm={async () => {
                  const rows = tableRef.current?.getSelectedRows() ?? [];
                  if (!rows.length) {
                    message.warning('请先选择字典');
                    return;
                  }
                  await dictApi.batchDelete(rows.map((row) => row.id));
                  message.success('批量删除成功');
                  tableRef.current?.reload();
                }}
              >
                <Button danger icon={<DeleteOutlined />}>
                  批量删除
                </Button>
              </Popconfirm>
            </PermissionGate>
          </Space>
        }
      />

      <DictModal
        open={modalOpen}
        dictId={currentDictId}
        onCancel={() => setModalOpen(false)}
        onSuccess={() => {
          setModalOpen(false);
          tableRef.current?.reload();
        }}
      />

      <DictSubItemsModal
        open={subItemsOpen}
        parentId={currentParentId}
        onCancel={() => setSubItemsOpen(false)}
      />
    </>
  );
}

// web/src/views/system/dict/index.vue
<template>
  <div class="dict-page">
    <BasicTable
      :columns="columns"
      :api="loadData"
      :use-search-form="true"
      :form-config="searchFormConfig"
      :show-action-column="true"
      @register="registerTable"
    >
      <template #toolbar>
        <a-button v-permission="'dict.create'" type="primary" @click="handleCreate">
          <template #icon><PlusOutlined /></template>
            新增
        </a-button>
        <a-button v-permission="'dict.delete'" danger @click="handleBatchDelete">
          <template #icon><DeleteOutlined /></template>
          批量删除
        </a-button>
      </template>

      <template #bodyCell="{ column, record }">
        <template v-if="column.dataIndex === 'status'">
          <a-tag :color="record.status === 0 ? 'success' : 'error'">
            {{ record.status === 0 ? '正常' : '停用' }}
          </a-tag>
        </template>
        <template v-else-if="column.dataIndex === 'isDefault'">
          <a-tag :color="record.isDefault ? 'success' : 'default'">
            {{ record.isDefault ? '是' : '否' }}
          </a-tag>
        </template>
        <template v-else-if="column.dataIndex === 'action'">
          <TableAction
            :actions="[
              {
                label: '编辑',
                onClick: () => handleEdit(record),
                ifShow: hasPermission('dict.update'),
              },
              {
                label: '编辑子项',
                onClick: () => handleEditSubItems(record),
                ifShow: hasPermission('dict.update'),
              },
              {
                label: '删除',
                color: 'error',
                popConfirm: {
                  title: '确定删除该字典吗？',
                  confirm: () => handleDelete(record.id),
                },
                ifShow: hasPermission('dict.delete'),
              },
            ]"
          />
        </template>
      </template>
    </BasicTable>

    <DictModal
      v-model:visible="modalVisible"
      :id="currentDictId"
      @success="handleSuccess"
    />

    <DictSubItemsModal
      v-model:visible="subItemsModalVisible"
      :parent-id="currentParentId"
    />
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { message } from 'ant-design-vue';
import { PlusOutlined, DeleteOutlined } from '@ant-design/icons-vue';
import BasicTable from '@/components/Table/BasicTable.vue';
import TableAction from '@/components/Table/TableAction.vue';
import DictModal from './DictModal.vue';
import DictSubItemsModal from './DictSubItemsModal.vue';
import { dictApi } from '@/api/dict';
import { usePermission } from '@/composables/usePermission';
import type { FormConfig } from '@/types/form';

const { hasPermission } = usePermission();

// 表格列配置
const columns = [
  {
    title: '字典ID',
    dataIndex: 'id',
    width: 80,
  },
  {
    title: '字典类型',
    dataIndex: 'dictType',
    width: 150,
  },
  {
    title: '字典标签',
    dataIndex: 'dictLabel',
    width: 150,
  },
  {
    title: '字典键值',
    dataIndex: 'dictValue',
    width: 150,
  },
  {
    title: '排序',
    dataIndex: 'sort',
    width: 80,
  },
  {
    title: '默认',
    dataIndex: 'isDefault',
    width: 80,
  },
  {
    title: '状态',
    dataIndex: 'status',
    width: 80,
  },
  {
    title: '创建时间',
    dataIndex: 'createdTime',
    width: 180,
  },
  {
    title: '操作',
    dataIndex: 'action',
    width: 150,
    fixed: 'right',
  },
];

// 搜索表单配置
const searchFormConfig: FormConfig = {
  schemas: [
    {
      field: 'dictType',
      label: '字典类型',
      component: 'Input',
      colProps: { span: 6 },
    },
    {
      field: 'dictLabel',
      label: '字典标签',
      component: 'Input',
      colProps: { span: 6 },
    },
    {
      field: 'status',
      label: '状态',
      component: 'Select',
      componentProps: {
        options: [
          { label: '正常', value: 0 },
          { label: '停用', value: 1 },
        ],
      },
      colProps: { span: 6 },
    },
  ],
};

// 表格实例
const tableRef = ref();
const registerTable = (methods: any) => {
  tableRef.value = methods;
};

// 加载数据
const loadData = async (params: any) => {
  const res = await dictApi.page(params);
  return {
    records: res.records || [],
    total: res.total || 0,
  };
};

// 弹窗状态
const modalVisible = ref(false);
const currentDictId = ref<number>();
const subItemsModalVisible = ref(false);
const currentParentId = ref<number>();

// 新增字典
const handleCreate = () => {
  currentDictId.value = undefined;
  modalVisible.value = true;
};

// 编辑字典
const handleEdit = (record: any) => {
  currentDictId.value = record.id;
  modalVisible.value = true;
};

// 删除字典
const handleDelete = async (id: number) => {
  try {
    await dictApi.delete(id);
    message.success('删除成功');
    tableRef.value?.reload();
  } catch (error) {
    console.error('删除失败:', error);
  }
};

// 批量删除
const handleBatchDelete = async () => {
  const selectedRows = tableRef.value?.getSelectRows();
  if (!selectedRows || selectedRows.length === 0) {
    message.warning('请选择要删除的字典');
    return;
  }
  try {
    const ids = selectedRows.map((row: any) => row.id);
    await dictApi.batchDelete(ids);
    message.success('批量删除成功');
    tableRef.value?.reload();
  } catch (error) {
    console.error('批量删除失败:', error);
  }
};

// 编辑子项
const handleEditSubItems = (record: any) => {
  currentParentId.value = record.id;
  subItemsModalVisible.value = true;
};

// 操作成功回调
const handleSuccess = () => {
  modalVisible.value = false;
  tableRef.value?.reload();
};
</script>

<style scoped lang="less">
.dict-page {
  padding: 0;
}
</style>
