// web/src/views/auth/login/index.vue
<template>
  <div class="login-container">
    <div class="login-box">
      <div class="login-header">
        <h1>{{ title }}</h1>
        <p>欢迎登录管理后台</p>
      </div>

      <a-form
        :model="formData"
        :rules="rules"
        @finish="handleLogin"
        layout="vertical"
        class="login-form"
      >
        <a-form-item name="username" label="用户名">
          <a-input
            v-model:value="formData.username"
            size="large"
            placeholder="请输入用户名"
            allow-clear
          >
            <template #prefix>
              <user-outlined />
            </template>
          </a-input>
        </a-form-item>

        <a-form-item name="password" label="密码">
          <a-input-password
            v-model:value="formData.password"
            size="large"
            placeholder="请输入密码"
            allow-clear
          >
            <template #prefix>
              <lock-outlined />
            </template>
          </a-input-password>
        </a-form-item>

        <a-form-item v-if="showCaptcha" name="code" label="验证码">
          <div class="captcha-wrapper">
            <a-input
              v-model:value="formData.code"
              size="large"
              placeholder="请输入验证码"
              allow-clear
              style="flex: 1"
            />
            <div class="captcha-image" @click="loadCaptcha">
              <img v-if="captchaImage" :src="captchaImage" alt="验证码" />
              <reload-outlined class="reload-icon" />
            </div>
          </div>
        </a-form-item>

        <a-form-item>
          <a-button
            type="primary"
            html-type="submit"
            size="large"
            :loading="loading"
            block
          >
            登录
          </a-button>
        </a-form-item>
      </a-form>
    </div>
  </div>
</template>

<script setup lang="ts">
import { reactive, ref, onMounted } from 'vue';
import { useRouter, useRoute } from 'vue-router';
import { message } from 'ant-design-vue';
import { UserOutlined, LockOutlined, ReloadOutlined } from '@ant-design/icons-vue';
import { useAuthStore } from '@/stores/auth';
import type { LoginParams } from '@/types/api';
import { captchaApi } from '@/api/captcha';

const router = useRouter();
const route = useRoute();
const authStore = useAuthStore();

const title = import.meta.env.VITE_APP_TITLE;
const loading = ref(false);
const showCaptcha = ref(false);
const captchaImage = ref('');
const uuid = ref('');

const formData = reactive({
  username: '',
  password: '',
  code: '',
});

const rules = {
  username: [{ required: true, message: '请输入用户名', trigger: 'blur' }],
  password: [{ required: true, message: '请输入密码', trigger: 'blur' }],
  code: [{ required: true, message: '请输入验证码', trigger: 'blur' }],
};

const loadCaptcha = async () => {
  try {
    const data = await captchaApi.generateImage();
    uuid.value = data.id;
    captchaImage.value = data.data.image;
  } catch (error: any) {
    message.error('加载验证码失败');
  }
};

const handleLogin = async () => {
  try {
    loading.value = true;

    const params: LoginParams = {
      grantType: 'password',
      username: formData.username,
      password: formData.password,
      clientKey: import.meta.env.VITE_CLIENT_KEY,
      clientSecret: import.meta.env.VITE_CLIENT_SECRET,
    };

    if (showCaptcha.value) {
      params.uuid = uuid.value;
      params.code = formData.code;
    }

    await authStore.login(params);

    message.success('登录成功');

    const redirect = (route.query.redirect as string) || '/';
    router.push(redirect);
  } catch (error: any) {
    message.error(error.message || '登录失败');
    if (showCaptcha.value) {
      await loadCaptcha();
      formData.code = '';
    }
  } finally {
    loading.value = false;
  }
};

onMounted(async () => {
  try {
    const types = await captchaApi.getEnabledTypes();
    if (types.includes('image')) {
      showCaptcha.value = true;
      await loadCaptcha();
    }
  } catch (error) {
    console.error('Failed to load captcha types:', error);
  }
});
</script>

<style scoped>
.login-container {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  height: 100%;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
}

.login-box {
  width: 400px;
  padding: 40px;
  background: #fff;
  border-radius: 8px;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);
}

.login-header {
  text-align: center;
  margin-bottom: 32px;
}

.login-header h1 {
  font-size: 24px;
  font-weight: 600;
  color: #333;
  margin-bottom: 8px;
}

.login-header p {
  font-size: 14px;
  color: #666;
}

.login-form {
  margin-top: 24px;
}

.captcha-wrapper {
  display: flex;
  gap: 12px;
  align-items: center;
}

.captcha-image {
  position: relative;
  width: 120px;
  height: 40px;
  cursor: pointer;
  border: 1px solid #d9d9d9;
  border-radius: 4px;
  overflow: hidden;
  flex-shrink: 0;
}

.captcha-image img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.captcha-image .reload-icon {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  font-size: 16px;
  color: rgba(0, 0, 0, 0.3);
  opacity: 0;
  transition: opacity 0.2s;
}

.captcha-image:hover .reload-icon {
  opacity: 1;
}
</style>

// web-react/src/pages/auth/login/index.tsx
import { useEffect, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { App, Button, Card, Form, Input, Space, Typography } from 'antd';
import { LockOutlined, ReloadOutlined, UserOutlined } from '@ant-design/icons';
import { authApi } from '@/api/auth';
import { useAuthStore } from '@/store/auth';

interface LoginFormValues {
  username: string;
  password: string;
  code?: string;
}

export default function LoginPage() {
  const [form] = Form.useForm<LoginFormValues>();
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const { message } = App.useApp();
  const isLoggedIn = useAuthStore((state) => state.isLoggedIn);
  const login = useAuthStore((state) => state.login);
  const [loading, setLoading] = useState(false);
  const [showCaptcha, setShowCaptcha] = useState(false);
  const [captchaId, setCaptchaId] = useState('');
  const [captchaImage, setCaptchaImage] = useState('');

  const loadCaptcha = async () => {
    try {
      const data = await authApi.getImageCaptcha();
      setCaptchaId(data.id);
      setCaptchaImage(String(data.data.image ?? ''));
    } catch {
      message.error('加载验证码失败');
    }
  };

  useEffect(() => {
    if (isLoggedIn) {
      navigate('/', { replace: true });
    }
  }, [isLoggedIn, navigate]);

  useEffect(() => {
    void (async () => {
      try {
        const types = await authApi.getCaptchaTypes();
        const enabled = types.includes('image');
        setShowCaptcha(enabled);

        if (enabled) {
          await loadCaptcha();
        }
      } catch {
        setShowCaptcha(false);
      }
    })();
  }, []);

  const handleFinish = async (values: LoginFormValues) => {
    setLoading(true);
    try {
      // 登录参数严格对齐 sys-api/auth.api，不沿用旧前端里可能出现的残留兼容字段。
      await login({
        clientKey: import.meta.env.VITE_CLIENT_KEY,
        clientSecret: import.meta.env.VITE_CLIENT_SECRET,
        grantType: 'password',
        username: values.username,
        password: values.password,
        code: values.code,
        uuid: captchaId || undefined,
      });

      message.success('登录成功');
      // 登录后优先回到用户原本想访问的页面，和旧后台行为保持一致。
      const redirect = searchParams.get('redirect') || '/';
      navigate(redirect, { replace: true });
    } catch (error) {
      message.error(error instanceof Error ? error.message : '登录失败');
      if (showCaptcha) {
        form.setFieldValue('code', '');
        await loadCaptcha();
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="login-page">
      <Card className="login-card" variant="borderless">
        <Space direction="vertical" size={8} style={{ width: '100%', marginBottom: 24 }}>
          <Typography.Title level={2} style={{ marginBottom: 0 }}>
            {import.meta.env.VITE_APP_TITLE}
          </Typography.Title>
          <Typography.Text type="secondary">
            React 重写版后台。保持功能等价，同时保证代码结构清晰、便于学习。
          </Typography.Text>
        </Space>

        <Form<LoginFormValues>
          form={form}
          layout="vertical"
          onFinish={(values) => void handleFinish(values)}
        >
          <Form.Item
            label="用户名"
            name="username"
            rules={[{ required: true, message: '请输入用户名' }]}
          >
            <Input
              allowClear
              prefix={<UserOutlined />}
              placeholder="请输入用户名"
              size="large"
            />
          </Form.Item>

          <Form.Item
            label="密码"
            name="password"
            rules={[{ required: true, message: '请输入密码' }]}
          >
            <Input.Password
              allowClear
              prefix={<LockOutlined />}
              placeholder="请输入密码"
              size="large"
            />
          </Form.Item>

          {showCaptcha ? (
            <Form.Item
              label="验证码"
              name="code"
              rules={[{ required: true, message: '请输入验证码' }]}
            >
              <div className="login-captcha">
                <Input placeholder="请输入验证码" size="large" />
                <div
                  className="login-captcha-image"
                  onClick={() => void loadCaptcha()}
                >
                  {captchaImage ? (
                    <img alt="验证码" src={captchaImage} style={{ width: '100%' }} />
                  ) : (
                    <ReloadOutlined />
                  )}
                </div>
              </div>
            </Form.Item>
          ) : null}

          <Form.Item style={{ marginBottom: 0 }}>
            <Button block htmlType="submit" loading={loading} size="large" type="primary">
              登录
            </Button>
          </Form.Item>
        </Form>
      </Card>
    </div>
  );
}
